{{- if contains "app" .Values.installMode }}
{{- if or (eq "aaa" .Values.serviceName) (eq "bbb" .Values.serviceName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "templateproject.fullname" $ }}-{{ $.Values.serviceName }}-httpscerts-secrets
  namespace: {{ $.Release.Namespace | quote }}
  labels: 
    app: {{ $.Values.serviceName }}
    {{- include "templateproject.labels" . | nindent 4 }}
type: Opaque
data:
{{- $httpscertsPath := printf "%s" (include "templateproject.httpscertscertsPath" $) }}
{{- range $path, $file :=  $.Files.Glob $httpscertscertsPath }}
    {{- $name := base $path }}
    {{ $name }}: {{ $.Files.Get $path | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- if false }}
#comment:
#mount path: /project/www/httpscerts/HD_xxxxxx.cer
#Dir Struc. must be fit below struc,
#hytechc/
#├── files/
#│   └── secrets/
#│       ├── alpha
#│       │   ├── au
#│       │   │   ├── HD_630045110000010.cer
#│       │   │   ├── HD_630045110000010.pfx
#│       │   ├── vt
#│       │   │   ├── HD_630045110000012.cer
#│       │   │   └── HD_630045110000012.pfx
#│       │   └── star
#│       │       ├── HD_630045110000053.cer
#│       │       └── HD_630045110000053.pfx
#│       └── prod
#│           ├── au
#│           │   ├── HD_630045110000010.cer
#│           │   ├── HD_630045110000010.pfx
#│           ├── vt
#│           │   ├── HD_630045110000012.cer
#│           │   └── HD_630045110000012.pfx
#│           └── star
#│               ├── HD_630045110000053.cer
#│               └── HD_630045110000053.pfx
{{- end }}