resources:
  limits:
    cpu: 1
    memory: 2048Mi
  requests:
    cpu: 0.5
    memory: 1024Mi
    
ingress:
  templateproject--tokyo:
    hostname: 
      - "templateproject-tokyo.eks.prod-xxx.com"
    mappingService:
      - serviceName: templateproject--tokyo
        port: 80
        path: "/(.*)"
        pathType: ImplementationSpecific
  templateproject--osaka:
    hostname: 
      - "templateproject-osaka.eks.prod-xxx.com"
    mappingService:
      - serviceName: templateproject--osaka
        port: 80
        path: "/(.*)"
        pathType: ImplementationSpecific
  service-templateproject-client:
    hostname: 
      - "templateproject.eks.prod-xxx.me"
      - "templateproject.eks.prod-xxx.com"
      - "templateproject-tokyo.eks.prod-xxx.com"
      - "templateproject-osaka.eks.prod-xxx.com"
    mappingService:
      - serviceName: service-templateproject-client
        port: 8080
        path: "/(api/.*)"
        pathType: ImplementationSpecific